# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    always_put_control_body_on_new_line: true
    curly_braces_in_flow_control_structures: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    file_names: true
    prefer_collection_literals: true
    prefer_single_quotes: false
    prefer_final_fields: true
    prefer_final_locals: true
    annotate_overrides: true
    prefer_relative_imports: true
