name: bonsai
version: 1.2.0
homepage: https://github.com/maks/bonsai_dart
publish_to: https://onepub.dev/api/sdpsdavuhn/
description: A tiny Dart logging package using dart:developer logging, API inspired by Android logging.

environment: 
  sdk: '>=2.13.0 <4.0.0'

dependencies: 
  logging: ^1.0.2

dev_dependencies: 
  lints: ^1.0.0
  test: ^1.16.0
