name: bonsai
description: A tiny Dart logging package using dart:developer logging, API inspired by Android logging.
version: 1.0.1
homepage: https://github.com/maks/bonsai_dart

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  logging: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
